# Generated by Django 5.1 on 2024-08-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
