# Generated by Django 5.1 on 2024-08-30 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('localization', models.CharField(max_length=255)),
                ('admin', models.ManyToManyField(related_name='admin_in_institution', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='users_in_institution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
