# Generated by Django 5.1 on 2024-08-31 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='admin',
            field=models.ManyToManyField(blank=True, null=True, related_name='admin_in_institution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institution',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_in_institution', to=settings.AUTH_USER_MODEL),
        ),
    ]
